- alias: "Turn on Living Room Lights"
  triggers:
    - trigger: state 
      entity_id:
        - device_tracker.eric_s_s24
        - device_tracker.galaxys24
      to: "home"
    - trigger: sun
      event: sunset
      offset: "00:30:00"
  conditions:
    - alias: "sun down"
      condition: state 
      entity_id: sun.sun
      state: "below_horizon"
    - alias: "at home"
      condition: zone
      entity_id: 
      - device_tracker.galaxys24
      state: zone.home
  actions:
    - action: scene.turn_on
      target:
        entity_id: scene.living_room_mid


